- name: Raspberry Pi 4 - Headless Docker Host Setup
  hosts: rp4
  become: true
  tasks:
    - name: Update system
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install security packages
      ansible.builtin.apt:
        name:
          - ufw
          - fail2ban
          - unattended-upgrades
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Enable unattended upgrades
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: '^{{ item.regexp }}'
        line: "{{ item.line }}"
        mode: '644'
        create: true
      with_items:
        - { regexp: 'APT::Periodic::Update-Package-Lists', line: 'APT::Periodic::Update-Package-Lists "1";' }
        - { regexp: 'APT::Periodic::Download-Upgradeable-Packages', line: 'APT::Periodic::Download-Upgradeable-Packages "1";' }
        - { regexp: 'APT::Periodic::AutocleanInterval', line: 'APT::Periodic::AutocleanInterval "7";' }
        - { regexp: 'APT::Periodic::Unattended-Upgrade', line: 'APT::Periodic::Unattended-Upgrade "1";' }

    - name: Configure unattended-upgrades to apply only security updates
      ansible.builtin.blockinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        marker: "// {mark} ANSIBLE MANAGED SECURITY BLOCK"
        block: |
          Unattended-Upgrade::Origins-Pattern {
            "origin=Debian,codename=${distro_codename},label=Debian-Security";
          };

    - name: Enable and configure UFW
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Disable SSH password login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      register: no_passwords

    - name: Restart SSH
      when: no_passwords.changed
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Add Docker repository and key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=arm64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker and Compose plugin
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Install Portainer (optional)
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:linux-arm64
        state: started
        restart_policy: always
        published_ports:
          - "9000:9000"
          - "8000:8000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
